services:
    server:
        build:
            context: ./
            dockerfile: Dockerfile
        image: blogmind-server
        container_name: blogmind-node-server
        volumes:
            - ./:/app
        ports:
            - "8000:8000"
        # depends_on:
        #     - mongo
        env_file: ./.env
        environment:
            - NODE_ENV=production
        networks:
            - app-network
    # mongo:
    #     image: mongo
    #     volumes:
    #         - data-volume:/data/db
    #     networks:
    #         - app-network
    #     logging:
    #         driver: none
    # client:
    #     build:
    #         context: ./client
    #         dockerfile: Dockerfile
    #     image: blogmind-client
    #     container_name: blogmind-react-client
    #     volumes:
    #         - ./client:/app
    #     env_file: ./.env
    #     environment:
    #         - NODE_ENV=production
    #     ports:
    #         - "5173:5173"
    #     networks:
    #         - app-network

networks:
    app-network:

volumes:
    data-volume:
